//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsRentalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rentals()
        {
            this.Returns = new HashSet<Returns>();
        }
    
        public int RentalID { get; set; }
        public int ClientID { get; set; }
        public int EquipmentID { get; set; }
        public System.DateTime RentalDate { get; set; }
        public System.DateTime PlannedReturnDate { get; set; }
        public string RentalType { get; set; }
        public int RentalPeriod { get; set; }
        public decimal TotalCost { get; set; }
        public string PaymentStatus { get; set; }
        public string Notes { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Equipment Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Returns> Returns { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
