//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsRentalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Returns
    {
        public int ReturnID { get; set; }
        public int RentalID { get; set; }
        public System.DateTime ActualReturnDate { get; set; }
        public string ReturnCondition { get; set; }
        public string DamageDescription { get; set; }
        public string ManagerComment { get; set; }
    
        public virtual Rentals Rentals { get; set; }
    }
}
